export interface VideoTutorial {
  id: string
  no: string
  title: string
  summary: string
  groupId: string
  groupName: string
  difficulty: string
  durationSeconds: number
  videoUrl: string
  coverUrl: string
}

export const VIDEO_TUTORIAL_GROUPS: { id: string; name: string }[] = [
  { id: 'getting-started', name: '快速上手' },
  { id: 'core-features', name: '核心功能' },
  { id: 'risk-control', name: '风控与安全' },
  { id: 'advanced', name: '进阶功能' },
]

export const VIDEO_TUTORIALS: VideoTutorial[] = [
  {
    id: '02-connect-mt5',
    no: '02',
    title: '登录并连接 MT5',
    summary: '第一次使用：登录牛牛 AI，绑定 MT5 实例并确认已连接。',
    groupId: 'getting-started',
    groupName: '快速上手',
    difficulty: '入门',
    durationSeconds: 23.75,
    videoUrl: '/videos/tutorials/02-connect-mt5.mp4',
    coverUrl: '/videos/tutorials/covers/02-connect-mt5.jpg',
  },
  {
    id: '03-auto-trading-basics',
    no: '03',
    title: '自动交易入门',
    summary: '打开算法交易开关，设置分析间隔与分析周期，让 AI 自动盯盘。',
    groupId: 'core-features',
    groupName: '核心功能',
    difficulty: '进阶',
    durationSeconds: 24.96,
    videoUrl: '/videos/tutorials/03-auto-trading-basics.mp4',
    coverUrl: '/videos/tutorials/covers/03-auto-trading-basics.jpg',
  },
  {
    id: '04-auto-trading-params',
    no: '04',
    title: '自动交易参数设置',
    summary: '交易方向、手数、止损止盈与分析周期模板的具体设置方法。',
    groupId: 'core-features',
    groupName: '核心功能',
    difficulty: '进阶',
    durationSeconds: 25.36,
    videoUrl: '/videos/tutorials/04-auto-trading-params.mp4',
    coverUrl: '/videos/tutorials/covers/04-auto-trading-params.jpg',
  },
  {
    id: '05-risk-review-mechanism',
    no: '05',
    title: '风控审核机制',
    summary: 'AI 如何决定是否开仓：开仓审核与持仓审核的判断逻辑。',
    groupId: 'risk-control',
    groupName: '风控与安全',
    difficulty: '必备',
    durationSeconds: 25.96,
    videoUrl: '/videos/tutorials/05-risk-review-mechanism.mp4',
    coverUrl: '/videos/tutorials/covers/05-risk-review-mechanism.jpg',
  },
  {
    id: '06-one-click-layout-lines',
    no: '06',
    title: '一键布局：自动划线',
    summary: '用自动划线解决不会画支撑阻力的难题，持仓明细一眼看清。',
    groupId: 'core-features',
    groupName: '核心功能',
    difficulty: '进阶',
    durationSeconds: 24.01,
    videoUrl: '/videos/tutorials/06-one-click-layout-lines.mp4',
    coverUrl: '/videos/tutorials/covers/06-one-click-layout-lines.jpg',
  },
  {
    id: '07-one-click-layout',
    no: '07',
    title: '一键布局完整教程',
    summary: '从行情判断到生成挂单方案、调整参数、提交 MT5 的完整流程。',
    groupId: 'core-features',
    groupName: '核心功能',
    difficulty: '进阶',
    durationSeconds: 26.61,
    videoUrl: '/videos/tutorials/07-one-click-layout.mp4',
    coverUrl: '/videos/tutorials/covers/07-one-click-layout.jpg',
  },
  {
    id: '08-ai-screenshot-analysis',
    no: '08',
    title: 'AI 截图分析',
    summary: '上传行情截图并输入提示词，让 AI 直接给出分析结论与方案。',
    groupId: 'core-features',
    groupName: '核心功能',
    difficulty: '进阶',
    durationSeconds: 23.92,
    videoUrl: '/videos/tutorials/08-ai-screenshot-analysis.mp4',
    coverUrl: '/videos/tutorials/covers/08-ai-screenshot-analysis.jpg',
  },
  {
    id: '09-ai-analysis-multi-plan',
    no: '09',
    title: 'AI 分析：多方案选择',
    summary: '同一行情下对比多套方案（突破打法／波段打法），挑选适合的一套。',
    groupId: 'core-features',
    groupName: '核心功能',
    difficulty: '进阶',
    durationSeconds: 24.66,
    videoUrl: '/videos/tutorials/09-ai-analysis-multi-plan.mp4',
    coverUrl: '/videos/tutorials/covers/09-ai-analysis-multi-plan.jpg',
  },
  {
    id: '10-trading-strategies',
    no: '10',
    title: '交易策略配置',
    summary: '交易策略板块与 EA 社区的作用，如何找到可复用的策略。',
    groupId: 'advanced',
    groupName: '进阶功能',
    difficulty: '高级',
    durationSeconds: 25.52,
    videoUrl: '/videos/tutorials/10-trading-strategies.mp4',
    coverUrl: '/videos/tutorials/covers/10-trading-strategies.jpg',
  },
  {
    id: '11-ai-model-execution',
    no: '11',
    title: 'AI 模型：开仓执行度',
    summary: '设置开仓执行度阈值，控制 AI 提交开仓的严格程度。',
    groupId: 'risk-control',
    groupName: '风控与安全',
    difficulty: '必备',
    durationSeconds: 25.96,
    videoUrl: '/videos/tutorials/11-ai-model-execution.mp4',
    coverUrl: '/videos/tutorials/covers/11-ai-model-execution.jpg',
  },
  {
    id: '12-position-monitoring',
    no: '12',
    title: '持仓监控与自动风控',
    summary: '持仓监控频率与强平机制，让持仓风险被持续看管。',
    groupId: 'risk-control',
    groupName: '风控与安全',
    difficulty: '必备',
    durationSeconds: 25.45,
    videoUrl: '/videos/tutorials/12-position-monitoring.mp4',
    coverUrl: '/videos/tutorials/covers/12-position-monitoring.jpg',
  },
  {
    id: '13-risk-control',
    no: '13',
    title: '风控设置完整教程',
    summary: '每日最大交易次数与最大亏损、新闻过滤、风控审核师。',
    groupId: 'risk-control',
    groupName: '风控与安全',
    difficulty: '必备',
    durationSeconds: 26.61,
    videoUrl: '/videos/tutorials/13-risk-control.mp4',
    coverUrl: '/videos/tutorials/covers/13-risk-control.jpg',
  },
  {
    id: '14-prompt-templates',
    no: '14',
    title: '提示词模板与自定义',
    summary: '修改提示词调整 AI 的分析偏好，改完立即生效。',
    groupId: 'advanced',
    groupName: '进阶功能',
    difficulty: '高级',
    durationSeconds: 25.54,
    videoUrl: '/videos/tutorials/14-prompt-templates.mp4',
    coverUrl: '/videos/tutorials/covers/14-prompt-templates.jpg',
  },
  {
    id: '15-ai-logs-review',
    no: '15',
    title: 'AI 日志与复盘',
    summary: '查看历史分析与开仓记录，用日志复盘自己的交易过程。',
    groupId: 'advanced',
    groupName: '进阶功能',
    difficulty: '高级',
    durationSeconds: 26.01,
    videoUrl: '/videos/tutorials/15-ai-logs-review.mp4',
    coverUrl: '/videos/tutorials/covers/15-ai-logs-review.jpg',
  },
  {
    id: '16-mt5-troubleshooting',
    no: '16',
    title: 'MT5 连接排错',
    summary: '连不上或绑定失败时，检查 EA 交易与允许自动交易开关。',
    groupId: 'getting-started',
    groupName: '快速上手',
    difficulty: '入门',
    durationSeconds: 24.15,
    videoUrl: '/videos/tutorials/16-mt5-troubleshooting.mp4',
    coverUrl: '/videos/tutorials/covers/16-mt5-troubleshooting.jpg',
  },
  {
    id: '17-account-niuqi-intro',
    no: '17',
    title: '账户与牛气值说明',
    summary: '账户信息在哪看、牛气值如何消耗与充值。',
    groupId: 'getting-started',
    groupName: '快速上手',
    difficulty: '入门',
    durationSeconds: 24.06,
    videoUrl: '/videos/tutorials/17-account-niuqi-intro.mp4',
    coverUrl: '/videos/tutorials/covers/17-account-niuqi-intro.jpg',
  },
  {
    id: '18-clone-analyst',
    no: '18',
    title: '克隆分析师',
    summary: '选周期、选指标、写提示词，生成属于你自己的 AI 分析师。',
    groupId: 'advanced',
    groupName: '进阶功能',
    difficulty: '高级',
    durationSeconds: 25.54,
    videoUrl: '/videos/tutorials/18-clone-analyst.mp4',
    coverUrl: '/videos/tutorials/covers/18-clone-analyst.jpg',
  },
]

export function getVideoTutorialsByGroup(groupId: string): VideoTutorial[] {
  return VIDEO_TUTORIALS.filter((v) => v.groupId === groupId)
}

export function formatDuration(seconds: number): string {
  return `${Math.round(seconds)} 秒`
}
